# Kubernetes Pod definition for an NGINX server
apiVersion: v1
kind: Pod
metadata:
  # The name of our pod
  name: nginx-pod
spec:
  containers:
    - name: nginx
      image: docker.io/library/nginx:latest
      ports:
        - containerPort: 80
          hostPort: 80
      volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
        - name: nginx-html
          mountPath: /usr/share/nginx/html
  volumes:
    # Define the host path for the nginx.conf volume
    - name: nginx-conf
      hostPath:
        path: /var/homelab/etc/nginx/nginx.conf
        type: File
    # Define the host path for the HTML content volume
    - name: nginx-html
      hostPath:
        path: /var/homelab/etc/nginx/html
        type: Directory
