---
apiVersion: v1
kind: Namespace
metadata:
  name: homelab
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    # allows distribution of gateway ca bundle
    # by trust-manager
    trust: "enabled"

---
# Certificate for Hypercore REST API
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hypercore-tls-cert
  namespace: homelab
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  secretName: hypercore-tls-secret
  issuerRef:
    # uses gateway root CA created in issuers.yaml
    # (homelab-selfsigned-ca)
    name: selfsigned-app-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - hypercore1.homelab.internal
    - hypercore2.homelab.internal
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: homelab-root-ca-bundle
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  sources:
    - secret:
        name: root-ca-secret
        key: ca.crt
  target:
    secret:
      key: root-ca.pem
      metadata:
        annotations:
          distributed-by: "trust-manager"
        labels:
          app: "trust-bundle"
    namespaceSelector:
      matchLabels:
        # allows distribution of gateway ca bundle into
        # the homelab namespace
        trust: "enabled"
