---
apiVersion: v1
kind: Namespace
metadata:
  name: homelab
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    # allows distribution of gateway ca bundle
    # by trust-manager
    trust: "enabled"

---
# Certificate for Hypercore REST API
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hypercore-tls-cert
  namespace: homelab
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  secretName: hypercore-tls-secret
  issuerRef:
    # uses gateway root CA created in issuers.yaml
    # (homelab-selfsigned-ca)
    name: selfsigned-app-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - hypercore1.homelab.internal
    - hypercore2.homelab.internal
