# This issuer is used to create a self-signed CA certificate.
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-selfsigned-ca
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  # Create CA root secret in `cert-manager` namespace instead of `sandbox` namespace.
  namespace: cert-manager
spec:
  isCA: true
  commonName: homelab-selfsigned-ca
  secretName: root-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
# This issuer is used to sign application certificates using the self-signed CA certificate.
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-app-issuer
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  ca:
    secretName: root-ca-secret
    # Secret is in cert-manager namespace
    # ClusterIssuers can access secrets in cert-manager namespace by default
