#!/usr/bin/env bash
# List cluster resources that still carry only the legacy
# `argocd.argoproj.io/instance` label and lack the modern
# `argocd.argoproj.io/tracking-id` annotation.
#
# Argo's prune logic enumerates resources via the modern annotation. Anything
# stuck on the legacy label is invisible to prune: when its manifest leaves
# Git, Argo silently skips it and the orphan stays alive forever (the failure
# mode hit in #48). This script flags those candidates so they can be
# re-applied (Argo writes both forms on apply) or `kubectl annotate`d to add
# the modern tracking-id by hand.
#
# Usage:
#   scripts/argocd-tracking-sweep.sh
#
# Exits non-zero when at least one stranded resource is found, so it can gate
# CI or be wired into a periodic check.
#
# Requires: kubectl (with cluster access), jq.

set -euo pipefail

require() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "missing required tool: $1" >&2
    exit 127
  fi
}

require kubectl
require jq

# Skipped on purpose:
#  - events / leases / endpointslices — controller-written, never Argo-managed.
#  - cilium.* — Cilium owns its own lifecycle; no Argo tracking expected.
#  - controllerrevisions — auto-generated by Deployment/DaemonSet/StatefulSet.
#  - pods — owned by their parent workload, never directly tracked by Argo.
#  - csistoragecapacities — written by the CSI driver.
NS_SKIP_RE='^(events|events.events.k8s.io|cilium.*|endpoints|endpointslices.discovery.k8s.io|leases.coordination.k8s.io|csistoragecapacities.storage.k8s.io|controllerrevisions.apps|pods)$'
CLUSTER_SKIP_RE='^(componentstatuses|nodes|cilium.*|tokenreviews|.*reviews\.authorization\.k8s\.io)$'

hits=0

scan_namespaced() {
  local kinds
  kinds="$(kubectl api-resources --namespaced=true --verbs=list -o name | grep -vE "$NS_SKIP_RE" || true)"
  local nss
  nss="$(kubectl get ns -o name | cut -d/ -f2)"
  local kind ns out
  for kind in $kinds; do
    for ns in $nss; do
      out="$(kubectl -n "$ns" get "$kind" -l argocd.argoproj.io/instance -o json 2>/dev/null \
        | jq -r '.items[]? | select(.metadata.annotations["argocd.argoproj.io/tracking-id"] == null) | "\(.kind)\t\(.metadata.namespace // "-")/\(.metadata.name)\tinstance=\(.metadata.labels["argocd.argoproj.io/instance"])"')"
      if [[ -n "$out" ]]; then
        printf '%s\n' "$out"
        hits=$((hits + 1))
      fi
    done
  done
}

scan_cluster_scoped() {
  local kinds
  kinds="$(kubectl api-resources --namespaced=false --verbs=list -o name | grep -vE "$CLUSTER_SKIP_RE" || true)"
  local kind out
  for kind in $kinds; do
    out="$(kubectl get "$kind" -l argocd.argoproj.io/instance -o json 2>/dev/null \
      | jq -r '.items[]? | select(.metadata.annotations["argocd.argoproj.io/tracking-id"] == null) | "\(.kind)\t\(.metadata.name)\tinstance=\(.metadata.labels["argocd.argoproj.io/instance"])"')"
    if [[ -n "$out" ]]; then
      printf '%s\n' "$out"
      hits=$((hits + 1))
    fi
  done
}

echo "==> namespaced resources"
scan_namespaced
echo "==> cluster-scoped resources"
scan_cluster_scoped

if [[ "$hits" -gt 0 ]]; then
  echo
  echo "FAIL: ${hits} stranded resource group(s) found." >&2
  exit 1
fi
echo
echo "OK: no stranded resources."
