config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/haljac/homelab
      targetRevision: main
applications:
  - name: metal-lb
    namespace: metallb-system
    syncWave: "-5"
    tool:
      helm:
        releaseName: metal-lb
  - name: envoy-gateway-system
    namespace: envoy-gateway-system
    syncWave: "-5"
    source:
      type: remote
      repoURL: oci://docker.io/envoyproxy/gateway-helm
      chart: gateway-helm
      targetRevision: v0.0.0-latest
    tool:
      helm:
        releaseName: eg
  - name: infrastructure
    syncWave: "0"
    tool:
      helm:
        releaseName: infrastructure
  - name: cert-manager
    namespace: cert-manager
    syncWave: "-10"
    source:
      type: remote
      repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.18.2
    tool:
      helm:
        releaseName: cert-manager
    values: |
      installCRDs: true
  - name: trust-manager
    namespace: cert-manager
    syncWave: "-9"
    source:
      type: remote
      repoURL: https://charts.jetstack.io
      chart: trust-manager
      targetRevision: v0.19.0
    tool:
      helm:
        releaseName: trust-manager
    values: |
      secretTargets:
        enabled: true
        authorizedSecrets:
          - homelab-root-ca-bundle
      app:
        trust:
          namespace: cert-manager
  - name: github-arc-controller
    namespace: arc-systems
    syncWave: "5"
    ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        jsonPointers:
          - /spec/preserveUnknownFields
    source:
      type: remote
      repoURL: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
      chart: gha-runner-scale-set-controller
      targetRevision: 0.12.1
    tool:
      helm:
        releaseName: arc-controller
  - name: github-arc-runners
    namespace: github-arc-runners
    syncWave: "5"
    source:
      type: remote
      repoURL: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
      chart: gha-runner-scale-set
      targetRevision: 0.12.1
    tool:
      helm:
        releaseName: arc-runners
    values: |
      githubConfigUrl: "https://github.com/haljac/homelab"
      githubConfigSecret:
        github_app_id: "1801903"
        github_app_installation_id: "81553437"
        github_app_private_key: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEpAIBAAKCAQEA2tM/T36X/+yErEZ/bgUb3/FC1AoBrzIEBb2DviIYxAIBG5O1
          IP6ONSnG+pBE/caSNlXm8wwGcOJVLe0PCtqBSkx1OuPrGi0s5wBlSBbPOqD/hP2Q
          ko2+7JR0HfBNK6c5ct9H6QZ1GA7s0JPZ2Iz642jAuiTOtY9LyZhoI8xDSo2Z460B
          HpAxbr4t6kwV3yw3kUoPs//8i8iNYjY199HfpTTe+BSNgOn0GL5GxFM+D1QouFRo
          Vn4x9azEwXhsZf6AAvYtVgTCKBbW5/9m7v7Z2o8b3WjOGIU7Z4KAO7DvqEyGlvwz
          nuQqMY7mwIrS6e9n2GHnYhJUcKWHP4yRyPu8gwIDAQABAoIBAQC1P6JB6v5leXeO
          5jmoXEzxWXlb/gnVHh1cz9NuSfmvaGWYfOjbMl2BxV/NrG+or6/tl4tapwwythWN
          m7wI5mGOs/Op2pyiKub1U0uQwWvWCQJ8GjaEXSnV9USUg7S3wqP/9NcwOSwFyF74
          iG45QtSQRfTUeaZJli5VBYrEk+zsswK8vQM7tRvWdn2a80sI9QLVNU3i1GrVR6Z2
          hKUhXaoX0hmObllNY/ZNqj1S62X7OfS4iwiEcZlPuLhnXmJfGeWxG+7Sjt9hx75N
          BpYPQMpbcvW0svQLD9sndJTRy17624MKpKTRfg5BbLVZDHVRJ/K1fsxDl0LS1CKJ
          dpYsPHEBAoGBAO0J+lSj8zjNvK1LRxrFJniRqbOmnx1gXcRz77XagzQ1x5D7rRvq
          dJGOFoTATuigewm866q671aRm20hWSJuzlfU2Nf3QyAnrvDl2JW7eg/ufklJ/Vgf
          SEoZM0fplE/Hooj6jnhoi4WxgTZDzuI3pawVUwPM7ahJB6wFeNgDxvmBAoGBAOxU
          Ss2tJzgK6X9ejUdeN0jB38aI5iv7Hjd6cwV5ZLSbC2mNp0RVf65z2JZwWZ00B7hm
          xUc5Roh+7OQ7vOeI/gDEriANm/KFGZ3lkX5HtqOUaE8OlJOMNqVL1umz7Q4XDAJO
          tvlFEzNGjk0biuCv9jaZIVurbIrxrzIJYPid7tADAoGAbpFa7aRUTcjaG9OjZT9V
          RKRdjmlIi0FqO7sAs8krrmzvnBdplj31BfhLVL0HkcdZ3R78pvTvs2fUIkGN/FvH
          cHzecU7rRtJ77e6o6p86vre2vKUAwdxFshqzKvYvsk8i59ZIIq5Rdpln9lIG7Mqc
          QvrncDxlFzyJkZoz1j9czwECgYEA5OTDSrABg0s2WlHGvi/nlcWJKm5fmItw+cTU
          cKHhwvdEN2imcA3rS5kSVqrccOD69UQ8oL49rWhZorilPw+1DCNyjsL/nwYBCKhX
          oZptr8PGv4NcrgeoybJJpjLJT9NMo1N/7rBTZ19X5iDeAr8K1li8MWA4Ed8Bk5H3
          5PR6X+cCgYAMCCzrCLJmcri+0als9rnjFtfSgLH6GvsRW8tofHP2J/+JVB5WIONX
          SKMkuFvew4CJJeGYIGiYeRRc6xRKKp+iku6YrJ7Jx70zSwhplHLePxA43a5hqX2a
          AX7VIZ4bP8sxLIIbze3GYNMDIgtx7XaSLD/UpUjpXHB9+wzBGQGfuw==
          -----END RSA PRIVATE KEY-----
