config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/haljac/homelab
      targetRevision: main
applications:
  - name: metal-lb
    namespace: metallb-system
    tool:
      helm:
        releaseName: metal-lb
  - name: envoy-gateway
    namespace: envoy-gateway-system
    source:
      type: remote
      repoURL: oci://docker.io/envoyproxy/gateway-helm
      chart: gateway-helm
      targetRevision: v0.0.0-latest
    tool:
      helm:
        releaseName: eg
