# /var/homelab/etc/nginx/nginx.conf

# Main Nginx process settings
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

# Main HTTP server block
http {
    include       /etc/nginx/mime.types;
    
    # You can remove the conf.d include line if all configuration is in this file.
    # include /etc/nginx/conf.d/*.conf;

    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    gzip  on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_min_length 256;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # This server block redirects all HTTP traffic to HTTPS.
    server {
        listen 80;
        server_name hypercore1.homelab.internal hypercore2.homelab.internal;
        return 301 https://$host$request_uri;
    }

    # You can keep a default server block for localhost if you want.
    server {
        listen 80 default_server;
        server_name localhost;

        root   /var/www/html;
        index  index.html index.htm;

        location / {
            try_files $uri $uri/ =404;
        }

        error_page 404 /404.html;
        location = /404.html {
            internal;
        }
    }
}

# This does TCP forwarding (SSL passthrough)
stream {
    # Define the upstream servers for the hypercore1 service.
    upstream hypercore1_backends_ssl {
        server 192.168.4.88:443;
        server 192.168.4.89:443;
        server 192.168.4.90:443;
    }

    # Define the upstream servers for the hypercore2 service.
    upstream hypercore2_backends_ssl {
        server 192.168.4.91:443;
        server 192.168.4.92:443;
        server 192.168.4.93:443;
    }
    
    # Map the incoming TLS traffic based on the SNI hostname.
    map $ssl_preread_server_name $backend_name {
        hypercore1.homelab.internal hypercore1_backends_ssl;
        hypercore2.homelab.internal hypercore2_backends_ssl;
        default hypercore1_backends_ssl;
    }

    # Listen for incoming TLS connections on port 443.
    server {
        listen 443;
	ssl_preread on;
        proxy_pass $backend_name;
    }
}

